npv: Teach to update version

diff --git a/bin/nuget-package-version b/bin/nuget-package-version
--- a/bin/nuget-package-version
+++ b/bin/nuget-package-version
@@ -6,10 +6,11 @@
 #           [<package-name>
 #               [(-v | --version)]
 #               [(-l | --list)]
+#               [(-u | --update) <version>]
 #           ]
 #
-# Show nuget package's version, files, etc. for given nuget package
-# name.
+# Show nuget package's version, files, etc. or update version for given
+# nuget package name.
 
 while true; do
 	case "$1" in
@@ -24,6 +25,26 @@ while true; do
 		-l | --list)
 			option="list"
 			shift ;;
+		-u | --update)
+			option="update"
+			shift
+			version="$1"
+			if [[ -z "$version" ]]; then
+				echo 1>&2 "fatal: version cannot be empty"
+				exit 1
+			fi
+			# 4-part version, from 1.2.x.x get 1.2.x|0.x|0
+			#version4parts=$(
+			#	sed -E \
+			#		'
+			#		/^[0-9]+(\.[0-9]+){1,3}$/ {
+			#			s,$,.0.0,
+			#			s,^([0-9]+(\.[0-9]+){3}).+,\1,
+			#		}
+			#		' <<< "$version"
+			#	)
+			shift
+			break ;;
 		-* )
 			if [ ! -z "$1" ]; then
 				echo 1>&2 "fatal: unknown option $1"
@@ -51,7 +72,7 @@ fi
 # text is of format
 #	<file>: <package-name> <version>
 text=$(
-	git grep -E -i "(Include|id)=.+ Version=" \
+	git grep -E -i "((Include|id)=.+ Version=)|(HintPath)" \
 		-- "*csproj" "*packages.config" | \
 	sed -E \
 		'
@@ -60,9 +81,8 @@ text=$(
 		s_([^:]+).*(Include|id)="([^"]+)".*Version="([^"]+)".*_\1: \3 \4_ i
 		# Reference: Include="name, Version=1.2.3.4
 		s_([^:]+).*Include="([^"]+),.*Version=([^,]+),.*_\1: \2 \3_ i
-		# remove last 0 from version as
-		#	1.2.3.0
-		s_(([0-9]+\.){2}[0-9]+)\.0_\1_
+		# Reference: <HintPath>..\..\packages\name.1.2.3
+		s_([^:]+).*<HintPath>.*\\([^\]+)\.([0-9]+(\.[0-9]+){2,3}).*_\1: \2 \3_ i
 		'
 	)
 
@@ -87,6 +107,30 @@ if [[ "$option" == "list" ]]; then
 		# remove package name
 		s,: [^ ]+ ,: ,
 		'
+	exit
+fi
+# update files for package (1 package only)
+if [[ "$option" == "update" ]]; then
+	# narrow down files for speed
+	git grep -E -i -l "$name" \
+		-- "*csproj" "*packages.config" | \
+	xargs -I_ \
+	sed -i -E \
+		'
+		# PackageReference: Include="name" Version="1.2.3"
+		s|(Include="'"$name"'") Version="[^"]+"|\1 Version="'"$version"'"|
+		# packages.config: id="name" version="1.2.3"
+		s|(id="'"$name"'") version="[^"]+"|\1 version="'"$version"'"|
+		# do not update Reference
+		# Reference: Include="name, Version=1.2.3.4
+		#s|(Include="'"$name"',) Version=[^,]+|\1 Version='"$version4parts"'|
+		# Reference: <HintPath>..\..\packages\name.1.2.3
+		#s|\\'"$name"'\.([0-9]+(\.[0-9]+){2,3})|\\'"$name"'.'"$version"'|
+		' _
+	# crlf file
+	git status -s | \
+		cuts | \
+		crlf-file
 	exit
 fi
 # list all
