remote: Consolidate validations

diff --git a/bin/remote b/bin/remote
--- a/bin/remote
+++ b/bin/remote
@@ -44,6 +44,23 @@ while true; do
 	esac
 done
 
+if [[ "$option" == "log" ]]; then
+	if [[ -z "$remoteBranch" ]]; then
+		echo 1>&2 "fatal: remoteBranch required"
+		exit 1
+	fi
+elif [[ "$option" == "commit" ]]; then
+	if [[ -z "$commit" ]]; then
+		echo 1>&2 "fatal: commit required"
+		exit 1
+	fi
+elif [[ "$option" == "tree" ]]; then
+	if [[ -z "$remoteBranch" ]]; then
+		echo 1>&2 "fatal: remoteBranch required"
+		exit 1
+	fi
+fi
+
 git config --get-regex remote\..*\.url \
 	| cut -d' ' -f2 \
 	| \
@@ -67,22 +84,10 @@ git config --get-regex remote\..*\.url \
 					exit 1
 				fi
 				if [[ "$option" == "log" ]]; then
-					if [[ -z "$remoteBranch" ]]; then
-						echo 1>&2 "fatal: remoteBranch required"
-						exit 1
-					fi
 					urlPart="commits/$remoteBranch"
 				elif [[ "$option" == "commit" ]]; then
-					if [[ -z "$commit" ]]; then
-						echo 1>&2 "fatal: commit required"
-						exit 1
-					fi
 					urlPart="commit/$commit"
 				elif [[ "$option" == "tree" ]]; then
-					if [[ -z "$remoteBranch" ]]; then
-						echo 1>&2 "fatal: remoteBranch required"
-						exit 1
-					fi
 					urlPart="browse/$remoteBranch/--/"
 				fi
 				sed '
@@ -94,22 +99,10 @@ git config --get-regex remote\..*\.url \
 				# others: github, gitlab, etc.
 				# add log, commit, tree specific url part
 				if [[ "$option" == "log" ]]; then
-					if [[ -z "$remoteBranch" ]]; then
-						echo 1>&2 "fatal: remoteBranch required"
-						exit 1
-					fi
 					urlPart="/commits/$remoteBranch"
 				elif [[ "$option" == "commit" ]]; then
-					if [[ -z "$commit" ]]; then
-						echo 1>&2 "fatal: commit required"
-						exit 1
-					fi
 					urlPart="/commit/$commit"
 				elif [[ "$option" == "tree" ]]; then
-					if [[ -z "$remoteBranch" ]]; then
-						echo 1>&2 "fatal: remoteBranch required"
-						exit 1
-					fi
 					urlPart="/tree/$remoteBranch"
 				fi
 				sed '
